---
plugins:
  - rubocop-minitest
  
# Apply latest style guide and new cops
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

# Ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - app/application/controllers/**/*.rb # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks
    - Rakefile # Rake namespaces produce large blocks

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile
    - app/infrastructure/database/migrations/*.rb

Naming/RescuedExceptionsVariableName:
  Enabled: false